import { TAX_PROPOSALS, TAX_PROPOSAL_SOURCE } from "@/lib/financial-constants/tax-proposals";
import { calculatePensionCap } from "@/lib/tax/proposal-planning";
import { cents } from "@/lib/tax/money";
import { euro, optionalPercent, percent, yesNo } from "../_tax_shared/form";
import type { TaxToolConfig } from "../_tax_shared/types";

export const config: TaxToolConfig = {
  title:"Pensioenplafond-check 2027–2032",intro:"Bekijk welk salarisdeel bij loonstijging boven de voorgestelde bevroren fiscale grens valt.",scope:"Dit is geen berekening van je pensioenuitkering. De indexatievergelijking is een eigen hypothetisch scenario.",empty:{},
  example:{salary:"135000",bonus:"5000",pensionable:"yes",growth:"3",indexation:"3",franchise:"18000",employee:"8",employer:"16"},
  fields:[{id:"salary",label:"Pensioengevend jaarsalaris 2026 (€)",type:"money"},{id:"bonus",label:"Jaarlijkse bonus (€)",type:"money"},{id:"pensionable",label:"Telt de bonus mee voor pensioen?",type:"select",options:yesNo},{id:"growth",label:"Verwachte salarisgroei per jaar (%)",type:"number",min:-99,max:100},{id:"indexation",label:"Hypothetische indexatie van de grens (%)",type:"number",min:-99,max:100},{id:"franchise",label:"Franchise van je pensioenregeling (€)",type:"money",help:"Het salarisdeel waarover je geen pensioenpremie betaalt; te vinden in je pensioenregeling."},{id:"employee",label:"Werknemerspremie (%)",type:"number",max:100,optional:true},{id:"employer",label:"Werkgeverspremie (%)",type:"number",max:100,optional:true}],
  calculate(f){const r=calculatePensionCap({salaryCents:cents(f.salary),bonusCents:cents(f.bonus),pensionableBonus:f.pensionable==="yes",growthPpm:percent(f,"growth"),indexationPpm:percent(f,"indexation"),franchiseCents:cents(f.franchise),employeePpm:optionalPercent(f,"employee"),employerPpm:optionalPercent(f,"employer")});return {conclusion:r.firstExcessYear?`Je scenario komt vanaf ${r.firstExcessYear} boven het plafond`:"Je scenario blijft onder het plafond",rows:[{label:"Cumulatief salarisdeel boven de grens",value:euro(r.cumulativeExcessCents)}],table:{headers:["Jaar","Salaris","Grens","Boven grens","Hypothetische grens","Verschil werknemerspremie","Verschil werkgeverspremie"],rows:r.rows.map(row=>[String(row.year),euro(row.salaryCents),euro(row.capCents),euro(row.excessCents),euro(row.indexedCapCents),row.employeeImpactCents===null?"Niet ingevuld":euro(row.employeeImpactCents),row.employerImpactCents===null?"Niet ingevuld":euro(row.employerImpactCents)])},warnings:["Dit salarisdeel is geen gemiste pensioenuitkering en geen nettoverlies.","Premieverschillen hangen af van je regeling en loonafspraken. Pensioen via je werkgever en lijfrente zijn verschillende regelingen."],steps:["Salarisgroei wordt voor ieder jaar vanaf 2027 toegepast op het salaris van het vorige jaar.","Een pensioengevende bonus wordt jaarlijks met hetzelfde ingevulde bedrag toegevoegd.","De premie-indicatie vergelijkt de pensioengrondslag na franchise onder de bevroren en hypothetisch geïndexeerde grens.","Bespreek met HR welke loonbestanddelen pensioengevend zijn, welke franchise geldt en wat de werkgever met het salaris boven de grens doet."],sources:[{title:"Belastingplan 2027 — §5.8",url:TAX_PROPOSAL_SOURCE}],version:TAX_PROPOSALS.version,verifiedAt:TAX_PROPOSALS.verifiedAt};},
};
