import type { MortgageAutomationProviderSpec } from "@/lib/browser-automation/types";

export const mortgageProviderSpecs: MortgageAutomationProviderSpec[] = [
  {
    id: "independer",
    name: "Independer",
    url: "https://www.independer.nl/hypotheek/info/maximale-hypotheek-berekenen",
    notes:
      "Publieke uitleg richt zich op maximale hypotheek, maandlasten en de 4,5x-vuistregel. De calculator kan per situatie extra vragen stellen.",
    fieldHints: [
      { key: "grossAnnualHouseholdIncome", keywords: ["inkomen", "bruto jaarinkomen", "gezamenlijk inkomen"] },
      { key: "grossAnnualPartnerIncome", keywords: ["partner", "gezamenlijk inkomen"] },
      { key: "annualMortgageRate", keywords: ["rente", "hypotheekrente", "toetsrente"] },
      { key: "fixedRatePeriodMonths", keywords: ["rentevast", "rentevaste periode", "looptijd rentevast"] },
      { key: "mortgageTermYears", keywords: ["looptijd", "duur", "termijn"] },
      { key: "monthlyDebtPayments", keywords: ["schuld", "lasten", "lening", "maandlast"] },
      { key: "ownFunds", keywords: ["eigen geld", "spaargeld"] },
      { key: "purchasePrice", keywords: ["koopprijs", "woningwaarde", "aankoopprijs"] },
      { key: "marketValue", keywords: ["woningwaarde", "marktwaarde"] },
      { key: "nhgRequested", keywords: ["nhg"], kind: "checkbox" },
      { key: "energyLabel", keywords: ["energielabel", "label"], kind: "select" },
      { key: "energySavingMeasuresAmount", keywords: ["verduurzaming", "energiebesparend", "verbouwing"] },
      { key: "hasStudentLoan", keywords: ["studieschuld", "duo"], kind: "checkbox" },
      { key: "studentLoanMonthlyPayment", keywords: ["studieschuld", "duo", "maandbedrag"] },
    ],
    submitButtonLabels: ["Bereken", "Bereken mijn hypotheek", "Maximale hypotheek berekenen"],
    resultSelectors: ["[data-testid*=result]", "[role=main]", "main", "body"],
  },
  {
    id: "abnamro",
    name: "ABN AMRO",
    url: "https://www.abnamro.nl/nl/prive/hypotheken/maximale-hypotheek-berekenen.html",
    notes:
      "ABN AMRO noemt expliciet 30 jaar looptijd, 10 jaar rentevast en 100% woningwaarde als leidende context.",
    fieldHints: [
      { key: "grossAnnualHouseholdIncome", keywords: ["inkomen", "bruto jaarinkomen"] },
      { key: "grossAnnualPartnerIncome", keywords: ["partner", "gezamenlijk inkomen"] },
      { key: "annualMortgageRate", keywords: ["rente", "hypotheekrente"] },
      { key: "fixedRatePeriodMonths", keywords: ["rentevast", "10 jaar"] },
      { key: "mortgageTermYears", keywords: ["looptijd", "30 jaar"] },
      { key: "monthlyDebtPayments", keywords: ["lening", "schuld", "lasten"] },
      { key: "ownFunds", keywords: ["eigen geld", "spaargeld"] },
      { key: "purchasePrice", keywords: ["koopprijs", "woningwaarde"] },
      { key: "marketValue", keywords: ["woningwaarde", "marktwaarde"] },
      { key: "nhgRequested", keywords: ["nhg"], kind: "checkbox" },
      { key: "energyLabel", keywords: ["energielabel", "label"], kind: "select" },
      { key: "energySavingMeasuresAmount", keywords: ["verduurzamen", "energiebesparend"] },
      { key: "hasStudentLoan", keywords: ["studieschuld", "duo"], kind: "checkbox" },
      { key: "studentLoanMonthlyPayment", keywords: ["studieschuld", "duo", "maandbedrag"] },
    ],
    submitButtonLabels: ["Bereken", "Bereken je maximale hypotheek", "Hypotheek berekenen"],
    resultSelectors: ["[data-testid*=result]", "[role=main]", "main", "body"],
  },
  {
    id: "rabobank",
    name: "Rabobank",
    url: "https://www.rabobank.nl/particulieren/hypotheek/hypotheek-berekenen",
    notes:
      "Rabobank presenteert de tool als schatting van maximale hypotheek en maandlasten, met nadruk op annuïtair en rentevast.",
    fieldHints: [
      { key: "grossAnnualHouseholdIncome", keywords: ["inkomen", "bruto jaarinkomen"] },
      { key: "grossAnnualPartnerIncome", keywords: ["partner", "gezamenlijk inkomen"] },
      { key: "annualMortgageRate", keywords: ["rente", "hypotheekrente"] },
      { key: "fixedRatePeriodMonths", keywords: ["rentevast", "10 jaar"] },
      { key: "mortgageTermYears", keywords: ["looptijd", "30 jaar"] },
      { key: "monthlyDebtPayments", keywords: ["lening", "schuld", "lasten"] },
      { key: "ownFunds", keywords: ["eigen geld", "spaargeld"] },
      { key: "purchasePrice", keywords: ["koopprijs", "woningwaarde"] },
      { key: "marketValue", keywords: ["woningwaarde", "marktwaarde"] },
      { key: "nhgRequested", keywords: ["nhg"], kind: "checkbox" },
      { key: "energyLabel", keywords: ["energielabel", "label"], kind: "select" },
      { key: "energySavingMeasuresAmount", keywords: ["verduurzamen", "energiebesparend"] },
      { key: "hasStudentLoan", keywords: ["studieschuld", "duo"], kind: "checkbox" },
      { key: "studentLoanMonthlyPayment", keywords: ["studieschuld", "duo", "maandbedrag"] },
    ],
    submitButtonLabels: ["Bereken", "Bereken je maximale hypotheek", "Bereken hypotheek"],
    resultSelectors: ["[data-testid*=result]", "[role=main]", "main", "body"],
  },
  {
    id: "ing",
    name: "ING",
    url: "https://www.ing.nl/particulier/hypotheken/hypotheek-berekenen",
    notes:
      "ING heeft een publieke hypotheekberekening met maandlasten en maximale hypotheek als hoofdoutput.",
    fieldHints: [
      { key: "grossAnnualHouseholdIncome", keywords: ["inkomen", "bruto jaarinkomen"] },
      { key: "grossAnnualPartnerIncome", keywords: ["partner", "gezamenlijk inkomen"] },
      { key: "annualMortgageRate", keywords: ["rente", "hypotheekrente"] },
      { key: "fixedRatePeriodMonths", keywords: ["rentevast", "10 jaar"] },
      { key: "mortgageTermYears", keywords: ["looptijd", "30 jaar"] },
      { key: "monthlyDebtPayments", keywords: ["lening", "schuld", "lasten"] },
      { key: "ownFunds", keywords: ["eigen geld", "spaargeld"] },
      { key: "purchasePrice", keywords: ["koopprijs", "woningwaarde"] },
      { key: "marketValue", keywords: ["woningwaarde", "marktwaarde"] },
      { key: "nhgRequested", keywords: ["nhg"], kind: "checkbox" },
      { key: "energyLabel", keywords: ["energielabel", "label"], kind: "select" },
      { key: "energySavingMeasuresAmount", keywords: ["verduurzamen", "energiebesparend"] },
      { key: "hasStudentLoan", keywords: ["studieschuld", "duo"], kind: "checkbox" },
      { key: "studentLoanMonthlyPayment", keywords: ["studieschuld", "duo", "maandbedrag"] },
    ],
    submitButtonLabels: ["Bereken", "Bereken je hypotheek", "Hypotheek berekenen"],
    resultSelectors: ["[data-testid*=result]", "[role=main]", "main", "body"],
  },
];
