import { TAX_PROPOSALS, TAX_PROPOSAL_SOURCE } from "@/lib/financial-constants/tax-proposals";
import { calculateTravel, type TravelInput } from "@/lib/tax/proposal-planning";
import { cents } from "@/lib/tax/money";
import { euro, number } from "../_tax_shared/form";
import type { TaxToolConfig } from "../_tax_shared/types";

export const config: TaxToolConfig = {
  title:"Reiskostenvergoeding-check",intro:"Vergelijk de fiscale ruimte bij 23 en 25 cent per kilometer voor een zelfgekozen periode in 2026 of 2027.",scope:"Feitelijke dagen, geen vaste 128/214-dagenregeling. Thuiswerk- en afwezigheidsdagen zijn afzonderlijke dagen zonder woon-werkrit.",empty:{},
  example:{distance:"20",scheduled:"220",home:"20",absent:"0",business:"0",paid:"1840",mode:"private",publicCosts:"0"},
  fields:[{id:"mode",label:"Hoe reis je?",type:"select",options:[{value:"private",label:"Eigen auto, fiets of lopen"},{value:"public-actual",label:"OV met vergoeding werkelijke kosten"},{value:"employer",label:"Auto of fiets van de werkgever"}]},
    {id:"distance",label:"Enkele reisafstand (km)",type:"number"},{id:"scheduled",label:"Geplande werkdagen in de periode",type:"number",max:366},{id:"home",label:"Dagen uitsluitend thuiswerken",type:"number",max:366},{id:"absent",label:"Vakantie-, ziekte- en andere afwezigheidsdagen",type:"number",max:366},{id:"business",label:"Overige zakelijke kilometers in de periode",type:"number"},{id:"paid",label:"Werkelijk ontvangen vergoeding in de periode (€)",type:"money"},{id:"publicCosts",label:"Werkelijke OV-kosten in de periode (€)",type:"money",visible:f=>f.mode==="public-actual"}],
  calculate(f) {const r=calculateTravel({distanceHundredthsKm:cents(f.distance),scheduledDays:number(f,"scheduled"),homeDays:number(f,"home"),absentDays:number(f,"absent"),businessHundredthsKm:cents(f.business),paidCents:cents(f.paid),mode:f.mode as TravelInput["mode"],publicCostsCents:f.mode==="public-actual"?cents(f.publicCosts):0});
    return {conclusion:"Dit is je fiscale ruimte voor de ingevulde periode",rows:[{label:"Maximaal vrijgesteld in dit scenario",value:euro(r.maximumCents)},{label:"Oude referentie",value:euro(r.referenceCents)},{label:"Extra ruimte door verhoging",value:euro(r.differenceCents)},{label:"Werkelijk ontvangen",value:euro(r.paidCents)},{label:"Onbenutte ruimte",value:euro(r.unusedCents)},{label:"Boven deze vrijstelling",value:euro(r.aboveExemptionCents)}],warnings:["Fiscale ruimte is geen recht op betaling. Je werkgever, cao of arbeidsovereenkomst bepaalt de vergoeding.","De verhoging wordt met terugwerkende kracht vanaf 1 januari 2026 gecodificeerd. De extra ruimte wordt niet automatisch uitbetaald.","Bij reizen met vervoer van de werkgever wordt geen extra kilometervergoeding voor dezelfde rit berekend."],steps:[`${r.travelDays} feitelijke reisdagen; enkele afstand wordt per dag tweemaal geteld.`,`Totaal ${r.distanceHundredthsKm/100} kilometer inclusief overige zakelijke ritten.`,"Bij OV op basis van werkelijke kosten vervangt dit bedrag de kilometervergoeding."],sources:[{title:"Belastingplan 2027 — §5.1",url:TAX_PROPOSAL_SOURCE}],version:TAX_PROPOSALS.version,verifiedAt:TAX_PROPOSALS.verifiedAt};},
};
